
'use server';

import { redirect } from 'next/navigation';
import {
  generateInvoice,
  generateInvoiceXml,
  getP12FromUrl,
  signXml,
  documentReception,
  documentAuthorization,
} from 'open-factura';
import type { Cliente, Producto } from '@/types';
import { clientes, productos } from '@/lib/data';
import { format } from 'date-fns';

// Helper function to find a customer by ID
const getCustomer = (id: string): Cliente | undefined => clientes.find(c => c.id === id);

// Helper function to find a product by ID
const getProduct = (id:string): Producto | undefined => productos.find(p => p.id === id);

const getFormaPago = (method: string): string => {
    switch (method) {
        case 'efectivo': return '01';
        case 'tarjeta': return '19';
        case 'transferencia': return '20';
        case 'otros': return '20';
        default: return '01';
    }
}

export async function createInvoice(formData: FormData) {
  const customerId = formData.get('customerId') as string;
  const paymentMethod = formData.get('paymentMethod') as string;
  const rawItems = formData.get('items') as string;
  
  const items: { productId: string; quantity: number; discount: number; }[] = JSON.parse(rawItems);

  const customer = getCustomer(customerId);
  if (!customer) {
    throw new Error('Cliente no encontrado');
  }

  // --- Construct payload for open-factura ---
  const today = new Date();
  const subtotal = Number(formData.get('subtotal'));
  const tax = Number(formData.get('tax'));
  const total = Number(formData.get('total'));
  
  // This should come from settings in a real app
  const infoTributaria = {
    ambiente: "1", // 1 (Pruebas) | 2 (Producción)
    tipoEmision: "1", // 1 (Emisión Normal)
    razonSocial: "ELAPIEL S.A.",
    nombreComercial: "Elapiel eFactura",
    ruc: "0999999999001",
    claveAcceso: "", // This will be generated by generateInvoice
    codDoc: "01", // 01 (Factura)
    estab: "001",
    ptoEmi: "001",
    secuencial: new Date().getTime().toString().slice(-9).padStart(9, '0'), // Needs proper sequential management
    dirMatriz: "AV. 9 DE OCTUBRE Y MALECON, GUAYAQUIL",
  };
  
  const infoFactura = {
    fechaEmision: format(today, 'dd/MM/yyyy'),
    dirEstablecimiento: "AV. 9 DE OCTUBRE Y MALECON, GUAYAQUIL",
    obligadoContabilidad: "SI",
    tipoIdentificacionComprador: customer.identificador.length === 13 ? '04' : (customer.identificador.length === 10 ? '05' : '07'),
    razonSocialComprador: customer.name,
    identificacionComprador: customer.identificador,
    direccionComprador: customer.address,
    totalSinImpuestos: subtotal,
    totalDescuento: items.reduce((acc, item) => {
        const product = getProduct(item.productId);
        if(!product) return acc;
        const itemPrice = product.price * item.quantity;
        return acc + (itemPrice * (item.discount / 100));
    }, 0),
    totalConImpuestos: {
      totalImpuesto: [
        {
          codigo: '2', // 2 (IVA)
          codigoPorcentaje: '4', // 2 (12%), 3 (14%), 4 (15%), 0 (0%), 6 (No Objeto), 7 (Exento)
          baseImponible: subtotal, // This needs to be calculated for the specific tax rate
          valor: tax,
        },
      ]
    },
    propina: 0,
    importeTotal: total,
    moneda: "DOLAR",
    pagos: {
        pago: [
            {
                formaPago: getFormaPago(paymentMethod),
                total: total,
            }
        ]
    }
  };

  const detalles = {
    detalle: items.map(item => {
        const product = getProduct(item.productId);
        if (!product) {
        throw new Error(`Producto con id ${item.productId} no encontrado`);
        }
        const itemTotalSinImpuesto = product.price * item.quantity * (1 - item.discount / 100);
        const discountAmount = product.price * item.quantity * (item.discount / 100);
        const iva = itemTotalSinImpuesto * product.taxRate;

        return {
            codigoPrincipal: product.code,
            descripcion: product.name,
            cantidad: item.quantity,
            precioUnitario: product.price,
            descuento: discountAmount,
            precioTotalSinImpuesto: itemTotalSinImpuesto,
            impuestos: {
                impuesto: [
                    {
                        codigo: '2', // IVA
                        codigoPorcentaje: '4', // 15%
                        tarifa: 15,
                        baseImponible: itemTotalSinImpuesto,
                        valor: iva
                    }
                ]
            }
        }
    })
  };

  // Choose SRI endpoints based on environment (default to 'test')
  const sriEnvironment = process.env.SRI_ENVIRONMENT || 'test'; // 'test' or 'production'
  const receptionUrl = sriEnvironment === 'production' 
    ? 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl'
    : 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/RecepcionComprobantesOffline?wsdl';
  const authorizationUrl = sriEnvironment === 'production'
    ? 'https://cel.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl'
    : 'https://celcer.sri.gob.ec/comprobantes-electronicos-ws/AutorizacionComprobantesOffline?wsdl';


  try {
    // 1. Generate Invoice object and access key
    const { invoice, accessKey } = generateInvoice({
      infoTributaria: {
          ...infoTributaria,
          ambiente: sriEnvironment === 'production' ? '2' : '1',
      },
      infoFactura,
      detalles,
    });

    // 2. Generate XML
    const invoiceXml = generateInvoiceXml(invoice);
    console.log("Clave de Acceso Generada:", accessKey);
    
    // 3. Sign XML
    // IMPORTANT: These must be set as environment variables in your hosting provider
    const p12Url = process.env.P12_URL; 
    const p12Password = process.env.P12_PASSWORD;

    if (!p12Url || !p12Password) {
      // We will log and skip signing for now if variables are not set.
      console.warn("ADVERTENCIA: No se configuraron las variables P12_URL y P12_PASSWORD. La factura fue generada pero no será firmada ni enviada al SRI.");
    } else {
        const p12Buffer = await getP12FromUrl(p12Url);
        const signedXml = await signXml(p12Buffer, p12Password, invoiceXml);
        console.log("XML Firmado con éxito.");

        // 4. Send to SRI for reception
        const receptionResult = await documentReception(signedXml, receptionUrl);
        console.log("Resultado de Recepción SRI:", receptionResult);

        if (receptionResult.estado !== 'RECIBIDA') {
            console.error("Error en la recepción del SRI:", receptionResult);
            throw new Error(`El SRI no recibió la factura. Estado: ${receptionResult.estado}`);
        }
        
        console.log("Factura RECIBIDA por el SRI.");

        // 5. Authorize document. This can take a few seconds.
        await new Promise(resolve => setTimeout(resolve, 3000)); // Wait 3 seconds before authorizing

        const authorizationResult = await documentAuthorization(accessKey, authorizationUrl);
        console.log("Resultado de Autorización SRI:", authorizationResult);

        // TODO: Process authorizationResult and save the final status and data to your database.
    }

  } catch (error) {
    console.error("Error en el proceso de facturación:", error);
    // TODO: Handle error in the UI, maybe return a message to the user or save invoice with 'Error' status
    throw error;
  }

  // If successful, redirect to invoices page
  redirect('/invoices');
}
